import { useEffect, useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiFetch } from '../../../api'
import './PlannedQuestionPages.css'

const optionMap = question => question.options || { A:question.option_a, B:question.option_b, C:question.option_c, D:question.option_d }
const difficultyOf = question => question.admin_override || question.difficulty_ai || question.difficulty_init || question.difficulty || '미정'
const statusLabel = status => ({ approved:'승인됨', reviewing:'검수 대기', rejected:'반려', archived:'보관' }[status] || status || '미정')
const statusTone = status => ['approved','완료','정상'].includes(status) ? 'ok' : ['reviewing','검토 필요'].includes(status) ? 'warn' : ''

function Header({ title, description, children }) { return <div className="qplan-head"><div><h1>{title}</h1><p>{description}</p></div><div className="qplan-actions">{children}</div></div> }
function Card({ title, action, children }) { return <section className="qplan-card">{title && <div className="qplan-card-head"><h2>{title}</h2>{action}</div>}<div className="qplan-card-body">{children}</div></section> }
function Badge({ children, tone='' }) { return <span className={`qplan-badge ${tone}`}>{children}</span> }

export function PlannedQuestionGeneration({ toast }) {
  const [teams,setTeams]=useState([]), [team,setTeam]=useState('T1'), [counts,setCounts]=useState({ common:5,team:10,safety:5,general:5 })
  const [evaluationType,setEvaluationType]=useState('기초고사')
  const [materials,setMaterials]=useState([]), [selectedMaterials,setSelectedMaterials]=useState([]), [loading,setLoading]=useState(false)
  const total=Object.values(counts).reduce((sum,value)=>sum+Number(value||0),0)
  const [diffCounts,setDiffCounts]=useState({ 하:8,중:12,상:5 })
  const diffTouched=useRef(false)
  useEffect(()=>{ if(diffTouched.current)return; const low=Math.round(total*.32),mid=Math.round(total*.48); setDiffCounts({ 하:low,중:mid,상:total-low-mid }) },[total])
  const diffTotal=Object.values(diffCounts).reduce((sum,value)=>sum+Number(value||0),0)
  const updateDiffCount=(key,value)=>{diffTouched.current=true;setDiffCounts(current=>({...current,[key]:value}))}
  useEffect(()=>{ apiFetch('GET','/api/admin/teams').then(data=>setTeams(data.teams||[])).catch(()=>setTeams([])) },[])
  useEffect(()=>{ apiFetch('GET',`/api/admin/materials/status?team_code=${encodeURIComponent(team)}`).then(data=>{ const rows=Object.entries(data.categories||{}).flatMap(([category,value])=>(value.files||value.new_files||[]).map(file=>({ ...file, category }))); setMaterials(rows); setSelectedMaterials(rows.filter(file=>file.index_status!=='진행 중').map(file=>file.id||file.name)) }).catch(()=>{setMaterials([]);setSelectedMaterials([])}) },[team])
  const teamOptions=teams.length?teams:[{team_code:'T1',team_name:'1팀'},{team_code:'T2',team_name:'2팀'},{team_code:'T3',team_name:'3팀'}]
  const updateCount=(key,value)=>setCounts(current=>({...current,[key]:value}))
  async function generate(){ if(total<=0)return toast('총 문항 수를 확인하세요.','error'); setLoading(true); try{ const data=await apiFetch('POST','/api/admin/generate-ai-questions',{team_code:team,material_text:`평가유형:${evaluationType}; 카테고리분포:${JSON.stringify(counts)}; 난이도분포:${JSON.stringify(diffCounts)}; 선택자료:${selectedMaterials.join(',')}`,count:total,difficulty_hint:'중'}); toast(`${data.questions?.length||0}문항을 생성해 검수 대기에 저장했습니다.`) }catch(error){toast(`문제 생성 실패: ${error.message}`,'error')}finally{setLoading(false)} }
  const sourceRows=materials.length?materials:[{id:'connected',name:'연결된 팀 교육자료',index_status:'색인 완료'}]
  return <section className="qplan"><Header title="문제 생성" description="출제 조건과 사용할 교육자료를 한 화면에서 구성합니다."><Link className="qplan-btn" to="/admin/questions/generate/runs">생성 작업 이력</Link><button className="qplan-btn primary" disabled={loading} onClick={generate}>{loading?'생성 중…':'문제 생성 실행'}</button></Header><div className="qplan-grid">
    <Card title="출제 대상"><div className="qplan-toggle-block"><span className="qplan-toggle-label">평가 유형</span><div className="qplan-toggle-group">{['기초고사','업무능력평가'].map(value=><button type="button" key={value} className={`qplan-toggle${evaluationType===value?' active':''}`} onClick={()=>setEvaluationType(value)}>{value}</button>)}</div></div><div className="qplan-toggle-block"><span className="qplan-toggle-label">대상 팀</span><div className="qplan-toggle-group">{teamOptions.map(item=><button type="button" key={item.team_code} className={`qplan-toggle${team===item.team_code?' active':''}`} onClick={()=>setTeam(item.team_code)}>{item.team_name}</button>)}</div></div></Card>
    <Card title="문항 구성"><div className="qplan-count-grid">{[['common','공통'],['team','팀'],['safety','환경안전'],['general','일반상식']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={counts[key]} onChange={e=>updateCount(key,e.target.value)}/></label>)}</div><div className="qplan-total"><span>총 문항 수</span><strong>{total}문항</strong></div><div className="qplan-diff-edit"><span>난이도 구성</span><div className="qplan-count-grid qplan-count-grid-3">{[['하','하'],['중','중'],['상','상']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={diffCounts[key]} onChange={e=>updateDiffCount(key,e.target.value)}/></label>)}</div>{diffTotal!==total&&<p className="qplan-diff-warning">난이도 합계 {diffTotal}문항이 총 문항 수 {total}문항과 다릅니다.</p>}</div></Card>
    <Card title="자료 선택">{sourceRows.map(file=>{const id=file.id||file.name;return <label className="qplan-source" key={id}><input type="checkbox" checked={selectedMaterials.includes(id)} onChange={()=>setSelectedMaterials(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id])}/><span>{file.name||file.file_name||id}</span><Badge tone={file.index_status==='진행 중'?'warn':'ok'}>{file.index_status||'색인 완료'}</Badge></label>})}</Card>
    <Card title="생성 정책"><div className="qplan-field-grid"><label>출제 방식<select><option>기존 문제 + 신규 생성</option><option>신규 생성</option></select></label><label>중복 제한<select><option>유사도 85% 이상 제외</option><option>유사도 90% 이상 제외</option></select></label><label>근거 필수<select><option>필수</option></select></label><label>문제 유형<select><option>객관식 4지선다</option></select></label></div></Card>
  </div><Card title="생성 전 검증"><div className="qplan-validation"><div><Badge tone={selectedMaterials.length?'ok':'warn'}>{selectedMaterials.length?'정상':'검토 필요'}</Badge><span>{selectedMaterials.length?`사용 가능한 자료 ${selectedMaterials.length}개 선택`:'선택 가능한 자료 상태를 확인하세요.'}</span></div><div><Badge tone={total>0?'ok':'warn'}>{total>0?'정상':'검토 필요'}</Badge><span>카테고리 문항 합계 {total}문항</span></div><div><Badge tone="warn">검토 필요</Badge><span>문제 부족분은 AI 신규 생성으로 보완하며 결과는 검수 대기로 저장됩니다.</span></div></div></Card></section>
}

export function PlannedGenerationRuns({ toast }){
  const [data,setData]=useState({jobs:[],enabled:true}),[loading,setLoading]=useState(true)
  useEffect(()=>{let active=true;setLoading(true);apiFetch('GET','/api/admin/generation-jobs').then(result=>{if(active)setData(result||{jobs:[],enabled:true})}).catch(error=>toast(`생성 작업 이력 조회 실패: ${error.message}`,'error')).finally(()=>active&&setLoading(false));return()=>{active=false}},[])
  const jobs=data.jobs||[]
  return <section className="qplan"><Header title="생성 작업 이력" description="AI 문제 생성 요청과 진행 상태를 확인합니다."><Link className="qplan-btn primary" to="/admin/questions/generate/setup">문제 생성으로</Link></Header>
    <Card>{loading?<div className="qplan-empty">불러오는 중…</div>:!data.enabled?<div className="qplan-empty">생성 작업 이력 저장소가 비활성화되어 있습니다.</div>:jobs.length===0?<div className="qplan-empty">아직 생성 작업이 없습니다.</div>:<div className="qplan-table-wrap"><table><thead><tr><th>작업 ID</th><th>요청자</th><th>상태</th><th>요청 수</th><th>완료</th><th>실패</th><th>시작 시각</th></tr></thead><tbody>{jobs.map(job=><tr key={job.generation_job_id}><td>{job.generation_job_id}</td><td>{job.requested_by||'-'}</td><td><Badge tone={job.status==='COMPLETED'?'ok':job.status==='FAILED'?'':'warn'}>{job.status||'-'}</Badge></td><td>{job.requested_count||'-'}</td><td>{job.completed_count||0}</td><td>{job.failed_count||0}</td><td>{job.started_at||'-'}</td></tr>)}</tbody></table></div>}</Card>
  </section>
}

export function PlannedQuestionReview({ toast }){
  const [items,setItems]=useState([]),[selectedId,setSelectedId]=useState(null),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[reason,setReason]=useState('')
  async function load(){setLoading(true);try{const data=await apiFetch('GET','/api/admin/questions?status=reviewing');setItems(data.questions||[]);setSelectedId(current=>current||(data.questions?.[0]?.question_id??null))}catch(error){toast(`검수 목록 조회 실패: ${error.message}`,'error')}finally{setLoading(false)}}
  useEffect(()=>{load()},[]); const visible=items.filter(item=>!search||item.question?.includes(search)||item.question_id?.includes(search)); const selected=items.find(item=>item.question_id===selectedId)||visible[0]
  async function approve(){if(!selected)return;try{await apiFetch('POST',`/api/admin/questions/${encodeURIComponent(selected.question_id)}/approve`);toast('문제를 승인했습니다.');await load()}catch(error){toast(`승인 실패: ${error.message}`,'error')}}
  async function reject(){if(!selected||!reason.trim())return toast('반려 사유를 입력하세요.','error');try{await apiFetch('POST',`/api/admin/questions/${encodeURIComponent(selected.question_id)}/reject`,{reason});toast('문제를 반려했습니다.');setReason('');await load()}catch(error){toast(`반려 실패: ${error.message}`,'error')}}
  async function updateDifficulty(value){if(!selected)return;try{await apiFetch('PATCH','/api/admin/difficulty',{question_id:selected.question_id,new_difficulty:value,reason_code:'검수수정'});setItems(current=>current.map(item=>item.question_id===selected.question_id?{...item,admin_override:value}:item));toast('난이도를 수정했습니다.')}catch(error){toast(`수정 실패: ${error.message}`,'error')}}
  return <section className="qplan"><Header title="검수 대기" description="AI 생성 문제를 수정하고 승인 또는 반려합니다."><button className="qplan-btn" disabled>일괄 반려</button><button className="qplan-btn primary" disabled>일괄 승인</button></Header><div className="qplan-toolbar"><input placeholder="문제 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select><option>전체 카테고리</option></select><select><option>전체 난이도</option></select><span className="spacer"/><Badge tone="warn">검수 대기 {visible.length}건</Badge></div><div className="qplan-review">
    <Card title="검수 목록">{loading?<div className="qplan-empty">불러오는 중…</div>:visible.length===0?<div className="qplan-empty">검수 대기 문제가 없습니다.</div>:<div className="qplan-table-wrap"><table><thead><tr><th>문제</th><th>분류</th><th>난이도</th><th>경고</th></tr></thead><tbody>{visible.map((item,index)=><tr data-clickable="true" className={selected?.question_id===item.question_id?'selected':''} key={`${item.question_id}-${index}`} onClick={()=>setSelectedId(item.question_id)}><td><strong>{item.question}</strong><small>{item.question_id}</small></td><td>{item.category||'-'}</td><td><Badge tone="warn">{difficultyOf(item)}</Badge></td><td><Badge tone="warn">{item.warning||item.validation_warning||'검토 필요'}</Badge></td></tr>)}</tbody></table></div>}</Card>
    <Card title="문제 상세">{!selected?<div className="qplan-empty">검수할 문제를 선택하세요.</div>:<div className="qplan-form"><label>문제 본문<textarea value={selected.question||''} readOnly/></label><div className="qplan-options">{Object.entries(optionMap(selected)).map(([key,value])=><label key={key}>{key}<input value={value||''} readOnly/></label>)}</div><div className="qplan-field-grid"><label>정답<input value={selected.answer||'정보 없음'} readOnly/></label><label>난이도<select value={difficultyOf(selected)} onChange={e=>updateDifficulty(e.target.value)}><option>하</option><option>중</option><option>상</option></select></label></div><label>해설<textarea value={selected.explanation||selected.rationale||'정보 없음'} readOnly/></label><label>근거 문서<input value={selected.source||selected.source_name||'정보 없음'} readOnly/></label><div className="qplan-preview">문제 본문·보기·해설 수정 API가 준비되지 않아 현재 저장된 정보만 표시합니다.</div><label>반려 사유<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="반려할 경우 사유 입력"/></label><div className="qplan-actions-bottom"><button className="qplan-btn danger" onClick={reject}>반려</button><button className="qplan-btn" disabled title="본문 수정 API 미지원">수정 저장</button><button className="qplan-btn primary" onClick={approve}>승인</button></div></div>}</Card>
  </div></section>
}

export function PlannedQuestionBank({ toast,filters,onFiltersChange,questionId }){
  const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[difficulty,setDifficulty]=useState('all'),[selectedId,setSelectedId]=useState(questionId)
  const query=useMemo(()=>{let path='/api/admin/questions?';if(filters.category)path+=`category=${encodeURIComponent(filters.category)}&`;if(filters.status&&filters.status!=='all')path+=`status=${filters.status}&`;return path},[filters])
  useEffect(()=>{let active=true;setLoading(true);apiFetch('GET',query).then(data=>{if(active){setItems(data.questions||[]);setSelectedId(current=>questionId||current||data.questions?.[0]?.question_id)}}).catch(error=>toast(`문제은행 조회 실패: ${error.message}`,'error')).finally(()=>active&&setLoading(false));return()=>{active=false}},[query,questionId])
  const visible=items.filter(item=>(!questionId||item.question_id===questionId)&&(!search||item.question?.includes(search)||item.question_id?.includes(search))&&(difficulty==='all'||difficultyOf(item)===difficulty));const selected=items.find(item=>item.question_id===selectedId&&(!questionId||item.question_id===questionId))||(questionId?null:visible[0]);const select=item=>setSelectedId(item.question_id)
  return <section className="qplan"><Header title={questionId?'문제 상세':'문제은행'} description="승인된 문제의 버전, 난이도, 사용 이력을 관리합니다.">{questionId&&<Link className="qplan-btn" to="/admin/questions/bank">← 목록으로</Link>}<button className="qplan-btn" disabled>Excel 내보내기</button><Link className="qplan-btn primary" to="/admin/exam-papers?tab=setup">시험 생성</Link></Header><div className="qplan-toolbar"><input aria-label="문제 또는 코드 검색" placeholder="문제 또는 코드 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="상태 필터" value={filters.status} onChange={e=>onFiltersChange({status:e.target.value})}><option value="all">전체 상태</option><option value="approved">승인됨</option><option value="reviewing">검수 대기</option><option value="rejected">반려</option></select><input aria-label="카테고리 필터" placeholder="전체 카테고리" value={filters.category} onChange={e=>onFiltersChange({category:e.target.value})}/><select aria-label="난이도 필터" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="all">전체 난이도</option><option>하</option><option>중</option><option>상</option></select><span className="spacer"/><Badge>{visible.length}문항</Badge></div><div className="qplan-bank">
    <Card>{loading?<div className="qplan-empty">불러오는 중…</div>:visible.length===0?<div className="qplan-empty">문제가 없습니다.</div>:<div className="qplan-table-wrap"><table><thead><tr><th>코드</th><th>문제</th><th>분류</th><th>난이도</th><th>상태</th><th>출제</th><th>버전</th><th>수정일</th></tr></thead><tbody>{visible.map((item,index)=><tr data-clickable="true" className={selected?.question_id===item.question_id?'selected':''} key={`${item.question_id}-${index}`} onClick={()=>select(item)}><td>{item.question_id}</td><td><strong>{item.question}</strong></td><td>{item.category||'-'}</td><td><Badge tone="warn">{difficultyOf(item)}</Badge></td><td><Badge tone={statusTone(item.status)}>{statusLabel(item.status)}</Badge></td><td>{item.exam_count??item.used_count??0}회</td><td>v{item.version||1}</td><td>{item.updated_at||item.updated||'-'}</td></tr>)}</tbody></table></div>}</Card>
    <Card title="문제 상세">{!selected?<div className="qplan-empty">문제를 선택하세요.</div>:<div className="qplan-form"><div className="qplan-detail"><span>문제 코드</span><strong>{selected.question_id}</strong></div><div className="qplan-detail"><span>문제 본문</span><strong>{selected.question}</strong></div><div className="qplan-field-grid"><label>난이도<input value={difficultyOf(selected)} readOnly/></label><label>상태<input value={statusLabel(selected.status)} readOnly/></label></div><div className="qplan-detail"><span>사용 이력</span><p>총 {selected.exam_count??selected.used_count??0}회 출제</p></div><button className="qplan-btn primary" disabled title="Revision 편집 API 미지원">상세 편집</button><div className="qplan-notice">확정 시험은 이 문제의 최신 수정과 무관하게 기존 Snapshot을 유지합니다.</div></div>}</Card>
  </div></section>
}
