import { Fragment, useEffect, useMemo, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { apiFetch } from '../../../api'
import './PlannedQuestionPages.css'

const optionMap = question => question.options || { A:question.option_a, B:question.option_b, C:question.option_c, D:question.option_d }
const difficultyOf = question => question.admin_override || question.difficulty_ai || question.difficulty_init || question.difficulty || '미정'
const statusLabel = status => ({ approved:'승인됨', reviewing:'검수 대기', rejected:'반려', archived:'보관' }[status] || status || '미정')
const statusTone = status => ['approved','완료','정상'].includes(status) ? 'ok' : ['reviewing','검토 필요'].includes(status) ? 'warn' : ''

function xmlEscape(value){ return String(value ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;') }
function downloadBlob(blob, filename){ const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=filename; a.click(); URL.revokeObjectURL(url) }
const BANK_EXPORT_HEADERS = ['코드','문제','분류','난이도','상태','출제','버전','수정일']
function exportQuestionsExcel(questions){
  const rows = questions.map(item=>[item.question_id,item.question,item.category||'-',difficultyOf(item),statusLabel(item.status),`${item.exam_count??item.used_count??0}회`,`v${item.version||1}`,item.updated_at||item.updated||'-'])
  const headerRow = `<Row>${BANK_EXPORT_HEADERS.map(h=>`<Cell ss:StyleID="Header"><Data ss:Type="String">${xmlEscape(h)}</Data></Cell>`).join('')}</Row>`
  const dataRows = rows.map(r=>`<Row>${r.map(v=>`<Cell><Data ss:Type="String">${xmlEscape(v)}</Data></Cell>`).join('')}</Row>`).join('')
  const xml = `<?xml version="1.0"?>\n<?mso-application progid="Excel.Sheet"?>\n<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">\n <Styles>\n  <Style ss:ID="Header"><Font ss:Bold="1"/><Interior ss:Color="#EEF2FF" ss:Pattern="Solid"/></Style>\n </Styles>\n <Worksheet ss:Name="문제은행">\n  <Table>\n   ${headerRow}\n   ${dataRows}\n  </Table>\n </Worksheet>\n</Workbook>`
  downloadBlob(new Blob([xml],{ type:'application/vnd.ms-excel' }), `문제은행_${questions.length}건.xls`)
}

function Header({ title, description, children }) { return <div className="qplan-head"><div><h1>{title}</h1><p>{description}</p></div><div className="qplan-actions">{children}</div></div> }
function Card({ title, action, children }) { return <section className="qplan-card">{title && <div className="qplan-card-head"><h2>{title}</h2>{action}</div>}<div className="qplan-card-body">{children}</div></section> }
function Badge({ children, tone='' }) { return <span className={`qplan-badge ${tone}`}>{children}</span> }

export function PlannedQuestionGeneration({ toast }) {
  const [teams,setTeams]=useState([]), [team,setTeam]=useState('T1'), [counts,setCounts]=useState({ common:5,team:10,safety:5,general:5 })
  const [evaluationType,setEvaluationType]=useState('기초고사')
  const [materials,setMaterials]=useState([]), [selectedMaterials,setSelectedMaterials]=useState([]), [loading,setLoading]=useState(false)
  const total=Object.values(counts).reduce((sum,value)=>sum+Number(value||0),0)
  const [diffCounts,setDiffCounts]=useState({ 하:8,중:12,상:5 })
  const diffTouched=useRef(false)
  useEffect(()=>{ if(diffTouched.current)return; const low=Math.round(total*.32),mid=Math.round(total*.48); setDiffCounts({ 하:low,중:mid,상:total-low-mid }) },[total])
  const diffTotal=Object.values(diffCounts).reduce((sum,value)=>sum+Number(value||0),0)
  const updateDiffCount=(key,value)=>{diffTouched.current=true;setDiffCounts(current=>({...current,[key]:value}))}
  useEffect(()=>{ apiFetch('GET','/api/admin/teams').then(data=>setTeams(data.teams||[])).catch(()=>setTeams([])) },[])
  useEffect(()=>{ apiFetch('GET',`/api/admin/materials/list?team_code=${encodeURIComponent(team)}`).then(data=>{ const rows=Object.entries(data.categories||{}).flatMap(([category,value])=>(value.files||[]).map(file=>({ ...file, category, categoryLabel:value.label }))); setMaterials(rows); setSelectedMaterials(rows.filter(file=>file.status==='synced').map(file=>file.id)) }).catch(()=>{setMaterials([]);setSelectedMaterials([])}) },[team])
  const teamOptions=teams.length?teams:[{team_code:'T1',team_name:'1팀'},{team_code:'T2',team_name:'2팀'},{team_code:'T3',team_name:'3팀'}]
  const updateCount=(key,value)=>setCounts(current=>({...current,[key]:value}))
  async function generate(){ if(total<=0)return toast('총 문항 수를 확인하세요.','error'); setLoading(true); try{ const data=await apiFetch('POST','/api/admin/generate-ai-questions',{team_code:team,material_text:`평가유형:${evaluationType}; 카테고리분포:${JSON.stringify(counts)}; 난이도분포:${JSON.stringify(diffCounts)}`,material_ids:selectedMaterials,count:total,difficulty_hint:'중'}); toast(`${data.questions?.length||0}문항을 생성해 검수 대기에 저장했습니다.`) }catch(error){toast(`문제 생성 실패: ${error.message}`,'error')}finally{setLoading(false)} }
  const materialStatusLabel=status=>status==='new'?'신규 반영 대기':status==='failed'?'추출 실패':'색인 완료'
  return <section className="qplan"><Header title="문제 생성" description="출제 조건과 사용할 교육자료를 한 화면에서 구성합니다."><Link className="qplan-btn" to="/admin/questions/generate/runs">생성 작업 이력</Link><button className="qplan-btn primary" disabled={loading} onClick={generate}>{loading?'생성 중…':'문제 생성 실행'}</button></Header><div className="qplan-grid">
    <Card><div className="qplan-subsection"><h3>출제 대상</h3><div className="qplan-toggle-block"><span className="qplan-toggle-label">평가 유형</span><div className="qplan-toggle-group">{['기초고사','업무능력평가'].map(value=><button type="button" key={value} className={`qplan-toggle${evaluationType===value?' active':''}`} onClick={()=>setEvaluationType(value)}>{value}</button>)}</div></div><div className="qplan-toggle-block"><span className="qplan-toggle-label">대상 팀</span><div className="qplan-toggle-group">{teamOptions.map(item=><button type="button" key={item.team_code} className={`qplan-toggle${team===item.team_code?' active':''}`} onClick={()=>setTeam(item.team_code)}>{item.team_name}</button>)}</div></div></div><div className="qplan-subsection"><h3>문항 구성</h3><div className="qplan-count-grid">{[['common','공통'],['team','팀'],['safety','환경안전'],['general','일반상식']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={counts[key]} onChange={e=>updateCount(key,e.target.value)}/></label>)}</div><div className="qplan-total"><span>총 문항 수</span><strong>{total}문항</strong></div><div className="qplan-diff-edit"><span>난이도 구성</span><div className="qplan-count-grid qplan-count-grid-3">{[['하','하'],['중','중'],['상','상']].map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={diffCounts[key]} onChange={e=>updateDiffCount(key,e.target.value)}/></label>)}</div>{diffTotal!==total&&<p className="qplan-diff-warning">난이도 합계 {diffTotal}문항이 총 문항 수 {total}문항과 다릅니다.</p>}</div></div></Card>
    <Card title="자료 선택">{materials.length===0?<p className="qplan-empty">연결된 교육자료가 없습니다. 자료·연동 화면에서 먼저 스캔해주세요.</p>:materials.map(file=><label className="qplan-source" key={file.id}><input type="checkbox" checked={selectedMaterials.includes(file.id)} onChange={()=>setSelectedMaterials(current=>current.includes(file.id)?current.filter(value=>value!==file.id):[...current,file.id])}/><span>{file.name} · {file.categoryLabel}</span><Badge tone={file.status==='synced'?'ok':'warn'}>{materialStatusLabel(file.status)}</Badge></label>)}</Card>
  </div></section>
}

export function PlannedGenerationRuns({ toast }){
  const [data,setData]=useState({jobs:[],enabled:true}),[loading,setLoading]=useState(true)
  const [openJobId,setOpenJobId]=useState(null),[detail,setDetail]=useState(null),[detailLoading,setDetailLoading]=useState(false)
  useEffect(()=>{let active=true;setLoading(true);apiFetch('GET','/api/admin/generation-jobs').then(result=>{if(active)setData(result||{jobs:[],enabled:true})}).catch(error=>toast(`생성 작업 이력 조회 실패: ${error.message}`,'error')).finally(()=>active&&setLoading(false));return()=>{active=false}},[])
  const jobs=data.jobs||[]
  async function toggleJob(jobId){
    if(openJobId===jobId){setOpenJobId(null);setDetail(null);return}
    setOpenJobId(jobId);setDetail(null);setDetailLoading(true)
    try{const result=await apiFetch('GET',`/api/admin/generation-jobs/${encodeURIComponent(jobId)}`);setDetail(result)}
    catch(error){toast(`작업 상세 조회 실패: ${error.message}`,'error');setOpenJobId(null)}
    finally{setDetailLoading(false)}
  }
  return <section className="qplan"><Header title="생성 작업 이력" description="AI 문제 생성 요청과 진행 상태를 확인합니다."><Link className="qplan-btn primary" to="/admin/questions/generate/setup">문제 생성으로</Link></Header>
    <Card>{loading?<div className="qplan-empty">불러오는 중…</div>:!data.enabled?<div className="qplan-empty">생성 작업 이력 저장소가 비활성화되어 있습니다.</div>:jobs.length===0?<div className="qplan-empty">아직 생성 작업이 없습니다.</div>:<div className="qplan-table-wrap"><table><thead><tr><th>작업 ID</th><th>요청자</th><th>상태</th><th>요청 수</th><th>완료</th><th>실패</th><th>시작 시각</th></tr></thead><tbody>{jobs.map(job=><Fragment key={job.generation_job_id}>
      <tr data-clickable="true" className={openJobId===job.generation_job_id?'selected':''} onClick={()=>toggleJob(job.generation_job_id)}><td>{job.generation_job_id}</td><td>{job.requested_by||'-'}</td><td><Badge tone={job.status==='COMPLETED'?'ok':job.status==='FAILED'?'':'warn'}>{job.status||'-'}</Badge></td><td>{job.requested_count||'-'}</td><td>{job.completed_count||0}</td><td>{job.failed_count||0}</td><td>{job.started_at||'-'}</td></tr>
      {openJobId===job.generation_job_id && <tr><td colSpan={7}><div className="qplan-job-detail">
        {detailLoading?'불러오는 중…':!detail?.enabled?'이 작업의 문제 상세를 조회할 수 없습니다.':!detail.candidates?.length?'이 작업에서 생성된 문제가 없습니다.':<table><thead><tr><th>문제</th><th>카테고리</th><th>난이도</th><th>Gate 상태</th><th>검수 상태</th></tr></thead><tbody>{detail.candidates.map(c=><tr key={c.candidate_id}><td>{c.question_text}</td><td>{c.category||'-'}</td><td>{c.difficulty_designed||'-'}</td><td><Badge tone={c.overall_gate_status==='PASS'?'ok':'warn'}>{c.overall_gate_status||'-'}</Badge></td><td>{c.review_status||c.status||'-'}</td></tr>)}</tbody></table>}
      </div></td></tr>}
    </Fragment>)}</tbody></table></div>}</Card>
  </section>
}

export function PlannedQuestionReview({ toast }){
  const [items,setItems]=useState([]),[selectedId,setSelectedId]=useState(null),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[reason,setReason]=useState('')
  const [checked,setChecked]=useState(()=>new Set()),[bulkBusy,setBulkBusy]=useState(false)
  const [edit,setEdit]=useState(null),[saving,setSaving]=useState(false)
  async function load(){setLoading(true);try{const data=await apiFetch('GET','/api/admin/questions?status=reviewing');setItems(data.questions||[]);setSelectedId(current=>current||(data.questions?.[0]?.question_id??null));setChecked(new Set())}catch(error){toast(`검수 목록 조회 실패: ${error.message}`,'error')}finally{setLoading(false)}}
  useEffect(()=>{load()},[]); const visible=items.filter(item=>!search||item.question?.includes(search)||item.question_id?.includes(search)); const selected=items.find(item=>item.question_id===selectedId)||visible[0]
  useEffect(()=>{ if(!selected){setEdit(null);return} const opts=optionMap(selected); setEdit({ question:selected.question||'', option_a:opts.A||'', option_b:opts.B||'', option_c:opts.C||'', option_d:opts.D||'', answer:selected.answer||'', explanation:selected.explanation||selected.rationale||'' }) },[selected?.question_id])
  function toggleCheck(id){ setChecked(current=>{ const next=new Set(current); next.has(id)?next.delete(id):next.add(id); return next }) }
  function toggleCheckAll(){ setChecked(current=>current.size===visible.length?new Set():new Set(visible.map(item=>item.question_id))) }
  async function approve(){if(!selected)return;try{await apiFetch('POST',`/api/admin/questions/${encodeURIComponent(selected.question_id)}/approve`);toast('문제를 승인했습니다.');await load()}catch(error){toast(`승인 실패: ${error.message}`,'error')}}
  async function reject(){if(!selected||!reason.trim())return toast('반려 사유를 입력하세요.','error');try{await apiFetch('POST',`/api/admin/questions/${encodeURIComponent(selected.question_id)}/reject`,{reason});toast('문제를 반려했습니다.');setReason('');await load()}catch(error){toast(`반려 실패: ${error.message}`,'error')}}
  async function updateDifficulty(value){if(!selected)return;try{await apiFetch('PATCH','/api/admin/difficulty',{question_id:selected.question_id,new_difficulty:value,reason_code:'검수수정'});setItems(current=>current.map(item=>item.question_id===selected.question_id?{...item,admin_override:value}:item));toast('난이도를 수정했습니다.')}catch(error){toast(`수정 실패: ${error.message}`,'error')}}
  async function saveEdit(){if(!selected||!edit)return;setSaving(true);try{await apiFetch('PATCH',`/api/admin/questions/${encodeURIComponent(selected.question_id)}`,edit);toast('문제 내용을 수정했습니다.');await load()}catch(error){toast(`수정 저장 실패: ${error.message}`,'error')}finally{setSaving(false)}}
  async function bulkApprove(){if(checked.size===0)return;if(!window.confirm(`선택한 ${checked.size}건을 일괄 승인할까요?`))return;setBulkBusy(true);try{const result=await apiFetch('POST','/api/admin/questions/bulk-approve',{question_ids:[...checked]});toast(`${result.succeeded}건 승인, ${result.failed}건 실패`);await load()}catch(error){toast(`일괄 승인 실패: ${error.message}`,'error')}finally{setBulkBusy(false)}}
  async function bulkReject(){if(checked.size===0)return;const bulkReason=window.prompt(`선택한 ${checked.size}건의 반려 사유를 입력하세요.`);if(!bulkReason||!bulkReason.trim())return;setBulkBusy(true);try{const result=await apiFetch('POST','/api/admin/questions/bulk-reject',{question_ids:[...checked],reason:bulkReason});toast(`${result.succeeded}건 반려, ${result.failed}건 실패`);await load()}catch(error){toast(`일괄 반려 실패: ${error.message}`,'error')}finally{setBulkBusy(false)}}
  return <section className="qplan"><Header title="검수 대기" description="AI 생성 문제를 수정하고 승인 또는 반려합니다."><button className="qplan-btn" disabled={checked.size===0||bulkBusy} onClick={bulkReject}>일괄 반려{checked.size>0?` (${checked.size})`:''}</button><button className="qplan-btn primary" disabled={checked.size===0||bulkBusy} onClick={bulkApprove}>일괄 승인{checked.size>0?` (${checked.size})`:''}</button></Header><div className="qplan-toolbar"><input placeholder="문제 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select><option>전체 카테고리</option></select><select><option>전체 난이도</option></select><span className="spacer"/><Badge tone="warn">검수 대기 {visible.length}건</Badge></div><div className="qplan-review">
    <Card title="검수 목록">{loading?<div className="qplan-empty">불러오는 중…</div>:visible.length===0?<div className="qplan-empty">검수 대기 문제가 없습니다.</div>:<div className="qplan-table-wrap"><table><thead><tr><th><input type="checkbox" checked={checked.size>0&&checked.size===visible.length} onChange={toggleCheckAll}/></th><th>문제</th><th>분류</th><th>난이도</th><th>경고</th></tr></thead><tbody>{visible.map((item,index)=><tr data-clickable="true" className={selected?.question_id===item.question_id?'selected':''} key={`${item.question_id}-${index}`} onClick={()=>setSelectedId(item.question_id)}><td onClick={e=>e.stopPropagation()}><input type="checkbox" checked={checked.has(item.question_id)} onChange={()=>toggleCheck(item.question_id)}/></td><td><strong>{item.question}</strong><small>{item.question_id}</small></td><td>{item.category||'-'}</td><td><Badge tone="warn">{difficultyOf(item)}</Badge></td><td><Badge tone="warn">{item.warning||item.validation_warning||'검토 필요'}</Badge></td></tr>)}</tbody></table></div>}</Card>
    <Card title="문제 상세">{!selected||!edit?<div className="qplan-empty">검수할 문제를 선택하세요.</div>:<div className="qplan-form"><label>문제 본문<textarea value={edit.question} onChange={e=>setEdit(current=>({...current,question:e.target.value}))}/></label><div className="qplan-options">{[['A','option_a'],['B','option_b'],['C','option_c'],['D','option_d']].map(([label,key])=><label key={key}>{label}<input value={edit[key]} onChange={e=>setEdit(current=>({...current,[key]:e.target.value}))}/></label>)}</div><div className="qplan-field-grid"><label>정답<input value={edit.answer} onChange={e=>setEdit(current=>({...current,answer:e.target.value}))}/></label><label>난이도<select value={difficultyOf(selected)} onChange={e=>updateDifficulty(e.target.value)}><option>하</option><option>중</option><option>상</option></select></label></div><label>해설<textarea value={edit.explanation} onChange={e=>setEdit(current=>({...current,explanation:e.target.value}))}/></label><label>근거 문서<input value={selected.source||selected.source_name||'정보 없음'} readOnly/></label><label>반려 사유<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="반려할 경우 사유 입력"/></label><div className="qplan-actions-bottom"><button className="qplan-btn danger" onClick={reject}>반려</button><button className="qplan-btn" disabled={saving} onClick={saveEdit}>{saving?'저장 중…':'수정 저장'}</button><button className="qplan-btn primary" onClick={approve}>승인</button></div></div>}</Card>
  </div></section>
}

export function PlannedQuestionBank({ toast,filters,onFiltersChange,questionId }){
  const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[difficulty,setDifficulty]=useState('all'),[selectedId,setSelectedId]=useState(questionId)
  const [editing,setEditing]=useState(false),[edit,setEdit]=useState(null),[saving,setSaving]=useState(false)
  const query=useMemo(()=>{let path='/api/admin/questions?';if(filters.category)path+=`category=${encodeURIComponent(filters.category)}&`;if(filters.status&&filters.status!=='all')path+=`status=${filters.status}&`;return path},[filters])
  function reload(){setLoading(true);return apiFetch('GET',query).then(data=>{setItems(data.questions||[]);setSelectedId(current=>questionId||current||data.questions?.[0]?.question_id)}).catch(error=>toast(`문제은행 조회 실패: ${error.message}`,'error')).finally(()=>setLoading(false))}
  useEffect(()=>{reload()},[query,questionId])
  const visible=items.filter(item=>(!questionId||item.question_id===questionId)&&(!search||item.question?.includes(search)||item.question_id?.includes(search))&&(difficulty==='all'||difficultyOf(item)===difficulty));const selected=items.find(item=>item.question_id===selectedId&&(!questionId||item.question_id===questionId))||(questionId?null:visible[0]);const select=item=>{setSelectedId(item.question_id);setEditing(false)}
  function startEdit(){ if(!selected)return; const opts=optionMap(selected); setEdit({ question:selected.question||'', option_a:opts.A||'', option_b:opts.B||'', option_c:opts.C||'', option_d:opts.D||'', answer:selected.answer||'', explanation:selected.explanation||selected.rationale||'' }); setEditing(true) }
  async function saveEdit(){if(!selected||!edit)return;setSaving(true);try{await apiFetch('PATCH',`/api/admin/questions/${encodeURIComponent(selected.question_id)}`,edit);toast('문제를 수정했습니다.');setEditing(false);await reload()}catch(error){toast(`수정 실패: ${error.message}`,'error')}finally{setSaving(false)}}
  async function updateBankDifficulty(value){if(!selected)return;try{await apiFetch('PATCH','/api/admin/difficulty',{question_id:selected.question_id,new_difficulty:value,reason_code:'문제은행수정'});toast('난이도를 수정했습니다.');await reload()}catch(error){toast(`난이도 수정 실패: ${error.message}`,'error')}}
  async function updateBankStatus(value){if(!selected)return;let reason='';if(value==='rejected'){reason=window.prompt('반려 사유를 입력하세요.')||'';if(!reason.trim())return}try{await apiFetch('PATCH',`/api/admin/questions/${encodeURIComponent(selected.question_id)}/status`,{status:value,reason});toast('상태를 변경했습니다.');await reload()}catch(error){toast(`상태 변경 실패: ${error.message}`,'error')}}
  return <section className="qplan"><Header title={questionId?'문제 상세':'문제은행'} description="승인된 문제의 버전, 난이도, 사용 이력을 관리합니다.">{questionId&&<Link className="qplan-btn" to="/admin/questions/bank">← 목록으로</Link>}<button className="qplan-btn" disabled={visible.length===0} onClick={()=>exportQuestionsExcel(visible)}>Excel 내보내기</button><Link className="qplan-btn primary" to="/admin/exam-papers?tab=setup">시험 생성</Link></Header><div className="qplan-toolbar"><input aria-label="문제 또는 코드 검색" placeholder="문제 또는 코드 검색" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="상태 필터" value={filters.status} onChange={e=>onFiltersChange({status:e.target.value})}><option value="all">전체 상태</option><option value="approved">승인됨</option><option value="reviewing">검수 대기</option><option value="rejected">반려</option></select><input aria-label="카테고리 필터" placeholder="전체 카테고리" value={filters.category} onChange={e=>onFiltersChange({category:e.target.value})}/><select aria-label="난이도 필터" value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option value="all">전체 난이도</option><option>하</option><option>중</option><option>상</option></select><span className="spacer"/><Badge>{visible.length}문항</Badge></div><div className="qplan-bank">
    <Card>{loading?<div className="qplan-empty">불러오는 중…</div>:visible.length===0?<div className="qplan-empty">문제가 없습니다.</div>:<div className="qplan-table-wrap"><table><thead><tr><th>코드</th><th>문제</th><th>분류</th><th>난이도</th><th>상태</th><th>출제</th><th>버전</th><th>수정일</th></tr></thead><tbody>{visible.map((item,index)=><tr data-clickable="true" className={selected?.question_id===item.question_id?'selected':''} key={`${item.question_id}-${index}`} onClick={()=>select(item)}><td>{item.question_id}</td><td><strong>{item.question}</strong></td><td>{item.category||'-'}</td><td><Badge tone="warn">{difficultyOf(item)}</Badge></td><td><Badge tone={statusTone(item.status)}>{statusLabel(item.status)}</Badge></td><td>{item.exam_count??item.used_count??0}회</td><td>v{item.version||1}</td><td>{item.updated_at||item.updated||'-'}</td></tr>)}</tbody></table></div>}</Card>
    <Card title="문제 상세">{!selected?<div className="qplan-empty">문제를 선택하세요.</div>:!editing?<div className="qplan-form"><div className="qplan-detail"><span>문제 코드</span><strong>{selected.question_id}</strong></div><div className="qplan-detail"><span>문제 본문</span><strong>{selected.question}</strong></div><div className="qplan-field-grid"><label>난이도<select value={difficultyOf(selected)} onChange={e=>updateBankDifficulty(e.target.value)}><option>하</option><option>중</option><option>상</option></select></label><label>상태<select value={selected.status||'reviewing'} onChange={e=>updateBankStatus(e.target.value)}><option value="approved">승인됨</option><option value="reviewing">검수 대기</option><option value="rejected">반려</option><option value="archived">보관</option></select></label></div><div className="qplan-detail"><span>사용 이력</span><p>총 {selected.exam_count??selected.used_count??0}회 출제</p></div><button className="qplan-btn primary" onClick={startEdit}>상세 편집</button><div className="qplan-notice">확정 시험은 이 문제의 최신 수정과 무관하게 기존 Snapshot을 유지합니다.</div></div>:<div className="qplan-form"><label>문제 본문<textarea value={edit.question} onChange={e=>setEdit(current=>({...current,question:e.target.value}))}/></label><div className="qplan-options">{[['A','option_a'],['B','option_b'],['C','option_c'],['D','option_d']].map(([label,key])=><label key={key}>{label}<input value={edit[key]} onChange={e=>setEdit(current=>({...current,[key]:e.target.value}))}/></label>)}</div><label>정답<input value={edit.answer} onChange={e=>setEdit(current=>({...current,answer:e.target.value}))}/></label><label>해설<textarea value={edit.explanation} onChange={e=>setEdit(current=>({...current,explanation:e.target.value}))}/></label><div className="qplan-actions-bottom"><button className="qplan-btn" onClick={()=>setEditing(false)}>취소</button><button className="qplan-btn primary" disabled={saving} onClick={saveEdit}>{saving?'저장 중…':'저장'}</button></div><div className="qplan-notice">확정 시험은 이 문제의 최신 수정과 무관하게 기존 Snapshot을 유지합니다.</div></div>}</Card>
  </div></section>
}
